# Introduction to NumPy

In [3]:
import numpy as np 

In [4]:
#to access the numpy help
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\OBED\\New folder\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\obed\new folder\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [5]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
#for strings 
L1 = [str(c) for c in L]
L1

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
L2 = [True, 7, "Mbwas", 4.784]

In [8]:
[type(item) for item in L2]

[bool, int, str, float]

# Fixed Type Arrays in Python 
In Python, a fixed-type array refers to an array where the data type of the elements is explicitly specified and remains consistent throughout the array. Unlike Python lists (which can hold mixed types), fixed-type arrays enforce a single data type, leading to better memory efficiency and faster computations.

In [9]:
import array 
#in the following example i indicates the integer. 
List = list(range(15))
A = array.array("i", List)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [10]:
#for float values 
A1 = array.array("f", [float(b) for b in List])
A1

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0])

# Creating arrays in numPy 
NumPy arrays (ndarray) are the backbone of numerical computing in Python. They provide a fast, memory-efficient, and convenient way to store and manipulate large datasets.

In [11]:
#let us start with list as array 
np.array([1,3,4,2,4,4])

array([1, 3, 4, 2, 4, 4])

In [12]:
#Remember that unlike Python lists, NumPy is constrained to arrays that all contain
#the same type. If types do not match, NumPy will upcast if possible (here, integers are
#upcast to floating point), that is, it converts the integers to float numbers.
np.array([1,2,2,3.24,12,23.4])

array([ 1.  ,  2.  ,  2.  ,  3.24, 12.  , 23.4 ])

In [13]:
#If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:
np.array([12,34,2.4,23,2.33], dtype="float")

array([12.  , 34.  ,  2.4 , 23.  ,  2.33])

In [14]:
#unlike Python lists, NumPy arrays can explicitly be multidimensional; 
np.array([range(i, i+3) for i in [2,3,4]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [15]:
#lets try a 5x5 array
np.array([range(i, i+5) for i in [2,3,4,5,6]])

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

# Creating an array from the scratch

In [16]:
#To create an array of 10 zeros that are zeroes 
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
#To create a 3x5 array of ones that float numbers 
np.ones((3, 5), dtype = "float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
#To create an array that is full of a certain number 
np.full((3,5), 3.45)

array([[3.45, 3.45, 3.45, 3.45, 3.45],
       [3.45, 3.45, 3.45, 3.45, 3.45],
       [3.45, 3.45, 3.45, 3.45, 3.45]])

# Creating Sequences in array

In [19]:
# To create an array of sequences, say from 0 to 20,with an interval of 2. 
#The arrange function evenly spaces the values based on the size while linspace does it based on the points 
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
#To create an array of numbers from 0 to 1 with an even points of 5
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.70927885, 0.93873581, 0.1055686 ],
       [0.77668982, 0.41114623, 0.66672965],
       [0.5311197 , 0.13267285, 0.0866482 ]])

In [22]:
np.random.random((4,4))

array([[0.03075151, 0.83184148, 0.98760297, 0.83852929],
       [0.43628813, 0.91918791, 0.46844353, 0.87043086],
       [0.16280619, 0.86477603, 0.1108724 , 0.00244158],
       [0.20910541, 0.05035553, 0.67595201, 0.77561519]])

In [23]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1, (3,3))

array([[ 1.11076299,  1.49282642,  1.07553659],
       [ 0.18943533,  0.39931937,  0.75643092],
       [ 0.02159072,  0.703262  , -1.9019047 ]])

In [24]:
 # Create a 3x3 array of random integers in the interval (0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 1, 6],
       [3, 9, 9],
       [3, 7, 7]])

In [25]:
 # Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
#I love 4x4 array more 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# The Basis of NumPy Arrays
We shall consider the following:
1. Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
2. Indexing of arrays: Getting and setting the value of individual array elements
3. Slicing of arrays: Getting and setting smaller subarrays within a larger array
4. Reshaping of arrays: Changing the shape of a given array
5. Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

# Attributes of arrays

Under the attributes we see the following features. 
1. arr.shape	
2. arr.ndim	
3. arr.size	
4. arr.dtype	
5. arr.itemsize	

In [27]:
#We shall be using a number generator for this
np.random.seed(0)
x1 = np.random.randint(10, size = 7)  # for 1dim array
x2 = np.random.randint(10, size = (3,4)) # for a 2dim array
x3 = np.random.randint(10, size = (3,4,5)) # for a 3dim array

In [28]:
x1

array([5, 0, 3, 3, 7, 9, 3])

In [29]:
x2

array([[5, 2, 4, 7],
       [6, 8, 8, 1],
       [6, 7, 7, 8]])

In [30]:
x3

array([[[1, 5, 9, 8, 9],
        [4, 3, 0, 3, 5],
        [0, 2, 3, 8, 1],
        [3, 3, 3, 7, 0]],

       [[1, 9, 9, 0, 4],
        [7, 3, 2, 7, 2],
        [0, 0, 4, 5, 5],
        [6, 8, 4, 1, 4]],

       [[9, 8, 1, 1, 7],
        [9, 9, 3, 6, 7],
        [2, 0, 3, 5, 9],
        [4, 4, 6, 4, 4]]])

In [31]:
print(f"The dimension of x1 is: ", x1.ndim)
print(f"The size of x1:", x1.size)
print(f"The shape of x1 is:", x1.shape)
print(f"The datatype of the array x1 is:", x1.dtype)

The dimension of x1 is:  1
The size of x1: 7
The shape of x1 is: (7,)
The datatype of the array x1 is: int32


In [32]:
print(f"The dimension of x1 is: ", x2.ndim)
print(f"The size of x1:", x2.size)
print(f"The shape of x1 is:", x2.shape)

The dimension of x1 is:  2
The size of x1: 12
The shape of x1 is: (3, 4)


In [33]:
print(f"The dimension of x1 is: ", x3.ndim)
print(f"The size of x1:", x3.size)
print(f"The shape of x1 is:", x3.shape)

The dimension of x1 is:  3
The size of x1: 60
The shape of x1 is: (3, 4, 5)


# indexing of arrays 
Indexing refers to accessing specific elements or subsets of an array. NumPy supports powerful indexing

In [34]:
#for select a single element 
x1

array([5, 0, 3, 3, 7, 9, 3])

In [35]:
x1[1]

0

In [36]:
#to index from the end, we use the negative indexing 
x1[-1]

3

In [37]:
#In a multidimensional array, you access items using a comma-separated tuple of indices:
x2

array([[5, 2, 4, 7],
       [6, 8, 8, 1],
       [6, 7, 7, 8]])

In [38]:
x2[0,0] #this code access the first element in the first row and column 

5

In [39]:
x2[2,3] #to access 8, that is, at row 3, column 3, the last element 

8

# Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use
them to access subarrays with the slice notation, marked by the colon (:). We use the syntax, x[start:stop:step]. If any of these are unspecified, they default to the values start=0, stop=size of
dimension, step=1.

In [40]:
#for 1dim subarrays 
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x[ :5]  #first five elements 

array([0, 1, 2, 3, 4])

In [42]:
x[5: ]  #elements after index 5

array([5, 6, 7, 8, 9])

In [43]:
x[4:7] #middle numbers 

array([4, 5, 6])

In [44]:
#or, you can use 
x[4:-3]

array([4, 5, 6])

In [45]:
# in reversed order 
x[ : :-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [46]:
#for multidimensional arrays 
x2

array([[5, 2, 4, 7],
       [6, 8, 8, 1],
       [6, 7, 7, 8]])

In [47]:
x2[:2, :3]
#before the comma, the first part is for the row and the column
#for the code, the row starts from the begining and then stops at index 2
#the column starts from the begining and then stops at column 3

array([[5, 2, 4],
       [6, 8, 8]])

In [48]:
x2[:3, ::3]

array([[5, 7],
       [6, 1],
       [6, 8]])

In [49]:
#Creating copies of sub Arrays 
x2_sub_copy = x2[:2,:3].copy()
x2_sub_copy

array([[5, 2, 4],
       [6, 8, 8]])

In [50]:
# Another useful type of operation is reshaping of arrays. The most flexible way of
#doing this is with the reshape() method

y = np.arange(1,10).reshape((3,3))

In [51]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
y1 = np.linspace(1,20, num=16).reshape((4,4))

In [53]:
y1

array([[ 1.        ,  2.26666667,  3.53333333,  4.8       ],
       [ 6.06666667,  7.33333333,  8.6       ,  9.86666667],
       [11.13333333, 12.4       , 13.66666667, 14.93333333],
       [16.2       , 17.46666667, 18.73333333, 20.        ]])

# Array Concatenation and Splitting

# Array Concatenation and Splitting
All of the preceding routines worked on single arrays. It’s also possible to combine
multiple arrays into one, and to conversely split a single array into multiple arrays.
We’ll take a look at those operations here.Concatenation of arrays
Concatenation, or joining of two arrays in NumPy, is primarily accomplished
through the routines np.concatenate, np.vstack, and np.hstack. np.concatenate
takes a tuple or list of arrays as its first argument, as we can see here:

In [54]:
#let us create a simple array of numbers and see how the concatenation works 
c1 = np.array([1,2,3,4,5])
c2 = np.array([6,7,8,9,10])

In [55]:
print(c1)
print(c2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [56]:
#to combine the two.
np.concatenate([c1,c2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
c3 = np.array([45,56,3,466,74,5])
np.concatenate([c1,c2,c3])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  45,  56,   3,
       466,  74,   5])

In [58]:
#We can use the concatenate for 2dim array too 

grid = np.array([[1,2,3], [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [60]:
# For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
#(vertical stack) and np.hstack (horizontal stack) functions:
x = np.array([1,2,3,4])
grid = np.array([[4,5,6,4], [2,3,4,6]])

In [61]:
## vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3, 4],
       [4, 5, 6, 4],
       [2, 3, 4, 6]])

# Computation on NumPy Arrays

# Operations with numpy 

np.add Addition 

np.subtract Subtraction 

np.negative Unary negation 

np.multiply Multiplication 

np.divide Division 

np.floor_divide Floor division 

np.power Exponentiation 

np.mod 

In [63]:
#to use the absolute value 
x = np.array([-2,-4,4,4-6,-6])
abs(x)

array([2, 4, 4, 2, 6])

In [66]:
#it can also handle complex number 
v = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
abs(v)

array([5., 5., 2., 1.])

# Trigonometry functions 

NumPy provides a large number of useful ufuncs, and some of the most useful for the
data scientist are the trigonometric functions

In [67]:
#to use the functions of the trig. let us define the angle of consideration 
theta = np.linspace(0, np.pi, 3)

In [71]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta)  =", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)  = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [73]:
#we can do the same for inverse tri. functions
x = np.array([-1, 0, 1])

In [77]:
print("x        =", x)
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

x        = [-1  0  1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


# Exponential and Logarithm functions 

In [78]:
x = np.array([1,2,3,4])

In [83]:
print("x             =", x)
print("e^x      =", np.exp(x))
print("e^2x     =", np.exp(2*x))
print("e^3x     =", np.exp(3*x))

x             = [1 2 3 4]
e^x      = [ 2.71828183  7.3890561  20.08553692 54.59815003]
e^2x     = [   7.3890561    54.59815003  403.42879349 2980.95798704]
e^3x     = [2.00855369e+01 4.03428793e+02 8.10308393e+03 1.62754791e+05]


In [84]:
x = np.array([2,3,4,5,6,7])

In [85]:
print("x     =", x)
print("log(x)=", np.log(x))
print("log(2x)=", np.log(2*x))

x     = [2 3 4 5 6 7]
log(x)= [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015]
log(2x)= [1.38629436 1.79175947 2.07944154 2.30258509 2.48490665 2.63905733]


# Summing values in the array
# Minimum and Maximum

In [86]:
d = np.random.random(100)

In [87]:
np.sum(d)

49.25524309863321

In [88]:
big_array = np.random.random(1000000)

In [89]:
np.min(big_array)

7.071203171893359e-07

In [90]:
np.max(big_array)

0.9999997207656334

In [91]:
#Multidimensional aggregates
V = np.random.random((3,3))

In [92]:
V

array([[0.29151563, 0.23485452, 0.00397991],
       [0.98768821, 0.02729722, 0.93858252],
       [0.21806917, 0.71465661, 0.53961311]])

In [93]:
np.sum(V)

3.956256906915331

In [94]:
#Aggregation functions take an additional argument specifying the axis along which
#the aggregate is computed. For example, we can find the minimum value within each
#column by specifying axis=0
V.min(axis=0)

array([0.21806917, 0.02729722, 0.00397991])

In [96]:
V.max(axis=1)

array([0.29151563, 0.98768821, 0.71465661])